language: java
jdk:
  - oraclejdk8

before_install:
  - chmod +x gradlew

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

jobs:
  include:
    - if: branch = master
      script: ./gradlew clean check
    - if: branch = dev
      script: ./gradlew clean check
    - if: branch != master AND branch != dev
      script: ./gradlew clean fastTest uiFastTest

after_script:
  zip -r build_artifacts.zip ./testfx-test*.png ./build/reports/*

addons:
  artifacts:
    s3_region: "us-east-1"
    paths:
      - build_artifacts.zip